server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: thebox-backend

  datasource:
    url: ${THEBOX_DB_URL}
    username: ${THEBOX_DB_USER}
    password: ${THEBOX_DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update               # Keeps tables in sync without dropping data
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: simple

# Logging
logging:
  level:
    com.thebox: DEBUG
    org.springframework.web: INFO

# Management / actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info
